//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public Userr()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
