//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_WPF_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BorrowRecords = new HashSet<BorrowRecord>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Category { get; set; }
        public string ISBN { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public string CoverImagePath { get; set; }
    
        public virtual ICollection<BorrowRecord> BorrowRecords { get; set; }
    }
}
