//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_WPF_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowRecord
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BookId { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
